-- Enable UUID extension for ID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users Table (Store Owners & Employees)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'cashier', -- 'owner', 'cashier', 'kitchen', 'admin'
    pin TEXT,
    store_id TEXT NOT NULL -- Used for multi-tenancy isolation
);

-- Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    store_id TEXT NOT NULL
);

-- Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0, -- -1 for unlimited
    barcode TEXT,
    store_id TEXT NOT NULL
);

-- Shifts Table
CREATE TABLE IF NOT EXISTS shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    cashier_id TEXT NOT NULL,
    start_cash NUMERIC DEFAULT 0,
    end_cash NUMERIC,
    total_sales NUMERIC DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'open', -- 'open', 'closed'
    store_id TEXT NOT NULL
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'cooking', 'ready', 'completed', 'cancelled'
    total NUMERIC NOT NULL DEFAULT 0,
    customer_name TEXT,
    shift_id BIGINT REFERENCES shifts(id),
    store_id TEXT NOT NULL
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1
);

-- Transactions Table (Payments)
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_id BIGINT REFERENCES orders(id),
    payment_method TEXT NOT NULL, -- 'cash', 'qris'
    amount NUMERIC NOT NULL,
    shift_id BIGINT REFERENCES shifts(id),
    store_id TEXT NOT NULL
);

-- Shopping Lists Table
CREATE TABLE IF NOT EXISTS shopping_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    date DATE NOT NULL,
    status TEXT DEFAULT 'active', -- 'active', 'completed', 'archived'
    items JSONB DEFAULT '[]'::jsonb, -- Array of items {id, name, price, quantity, unit}
    total_estimated NUMERIC DEFAULT 0,
    store_id TEXT NOT NULL
);

-- Shopping Items Catalog (for autocomplete)
CREATE TABLE IF NOT EXISTS shopping_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'pcs',
    store_id TEXT NOT NULL
);

-- Settings Table
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    value TEXT,
    store_id TEXT NOT NULL,
    UNIQUE(store_id, key)
);

-- RLS Policies (Optional but Recommended)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopping_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE shopping_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Simple Policy: Allow everything for now (since auth is handled in app via store_id filter)
-- Ideally, you should verify store_id matches the auth user's store_id
CREATE POLICY "Enable all access for now" ON users FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON categories FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON products FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON shifts FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON orders FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON order_items FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON transactions FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON shopping_lists FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON shopping_items FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON settings FOR ALL USING (true);
